# Generated by Django 4.2.5 on 2023-09-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee_name', models.CharField(max_length=100)),
                ('time_slot_a', models.CharField(max_length=1)),
                ('time_slot_b', models.CharField(max_length=1)),
                ('time_slot_c', models.CharField(max_length=1)),
                ('time_slot_d', models.CharField(max_length=1)),
            ],
        ),
    ]
